namespace _25736_24122_Calculadora;

partial class Form1
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }


    private void InitializeComponent()
    {
        txtVisor = new TextBox();
        txtResultado = new TextBox();
        lbSequencias = new Label();
        btnIgual = new Button();
        btnLimpar = new Button();
        btnApagar = new Button();
        tableBotoes = new TableLayoutPanel();
        btn7 = new Button();
        btn8 = new Button();
        btn9 = new Button();
        btnDividir = new Button();
        btnAbrir = new Button();
        btn4 = new Button();
        btn5 = new Button();
        btn6 = new Button();
        btnMultiplicar = new Button();
        btnFechar = new Button();
        btn1 = new Button();
        btn2 = new Button();
        btn3 = new Button();
        btnSubtrair = new Button();
        btnPotencia = new Button();
        btn0 = new Button();
        btnVirgula = new Button();
        btnSomar = new Button();
        tableBotoes.SuspendLayout();
        SuspendLayout();
        txtVisor.Font = new Font("Segoe UI", 18F);
        txtVisor.Location = new Point(22, 22);
        txtVisor.Name = "txtVisor";
        txtVisor.Size = new Size(426, 39);
        txtVisor.TabIndex = 0;
        txtVisor.TextAlign = HorizontalAlignment.Right;
        txtVisor.KeyPress += txtVisor_KeyPress;
        txtVisor.TextChanged += txtVisor_TextChanged;
        txtResultado.BackColor = SystemColors.Window;
        txtResultado.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
        txtResultado.Location = new Point(22, 75);
        txtResultado.Name = "txtResultado";
        txtResultado.ReadOnly = true;
        txtResultado.Size = new Size(426, 39);
        txtResultado.TabIndex = 1;
        txtResultado.TextAlign = HorizontalAlignment.Right;
        lbSequencias.BorderStyle = BorderStyle.FixedSingle;
        lbSequencias.Font = new Font("Segoe UI", 10F);
        lbSequencias.Location = new Point(22, 376);
        lbSequencias.Name = "lbSequencias";
        lbSequencias.Padding = new Padding(8);
        lbSequencias.Size = new Size(426, 95);
        lbSequencias.TabIndex = 2;
        lbSequencias.Text = "Sequencias:";
        btnIgual.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
        btnIgual.Location = new Point(22, 485);
        btnIgual.Name = "btnIgual";
        btnIgual.Size = new Size(426, 48);
        btnIgual.TabIndex = 3;
        btnIgual.Text = "=";
        btnIgual.UseVisualStyleBackColor = true;
        btnIgual.Click += btnIgual_Click;
        btnLimpar.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        btnLimpar.Location = new Point(22, 128);
        btnLimpar.Name = "btnLimpar";
        btnLimpar.Size = new Size(136, 42);
        btnLimpar.TabIndex = 4;
        btnLimpar.Text = "C";
        btnLimpar.UseVisualStyleBackColor = true;
        btnLimpar.Click += btnLimpar_Click;
        btnApagar.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        btnApagar.Location = new Point(164, 128);
        btnApagar.Name = "btnApagar";
        btnApagar.Size = new Size(284, 42);
        btnApagar.TabIndex = 5;
        btnApagar.Text = "Apagar";
        btnApagar.UseVisualStyleBackColor = true;
        btnApagar.Click += btnApagar_Click;
        tableBotoes.ColumnCount = 5;
        tableBotoes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        tableBotoes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        tableBotoes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        tableBotoes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        tableBotoes.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
        tableBotoes.Controls.Add(btn7, 0, 0);
        tableBotoes.Controls.Add(btn8, 1, 0);
        tableBotoes.Controls.Add(btn9, 2, 0);
        tableBotoes.Controls.Add(btnDividir, 3, 0);
        tableBotoes.Controls.Add(btnAbrir, 4, 0);
        tableBotoes.Controls.Add(btn4, 0, 1);
        tableBotoes.Controls.Add(btn5, 1, 1);
        tableBotoes.Controls.Add(btn6, 2, 1);
        tableBotoes.Controls.Add(btnMultiplicar, 3, 1);
        tableBotoes.Controls.Add(btnFechar, 4, 1);
        tableBotoes.Controls.Add(btn1, 0, 2);
        tableBotoes.Controls.Add(btn2, 1, 2);
        tableBotoes.Controls.Add(btn3, 2, 2);
        tableBotoes.Controls.Add(btnSubtrair, 3, 2);
        tableBotoes.Controls.Add(btnPotencia, 4, 2);
        tableBotoes.Controls.Add(btn0, 0, 3);
        tableBotoes.Controls.Add(btnVirgula, 1, 3);
        tableBotoes.Controls.Add(btnSomar, 3, 3);
        tableBotoes.Location = new Point(22, 183);
        tableBotoes.Name = "tableBotoes";
        tableBotoes.RowCount = 4;
        tableBotoes.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
        tableBotoes.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
        tableBotoes.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
        tableBotoes.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
        tableBotoes.Size = new Size(426, 180);
        tableBotoes.TabIndex = 6;
        btn7.Dock = DockStyle.Fill;
        btn7.Font = new Font("Segoe UI", 12F);
        btn7.Location = new Point(3, 3);
        btn7.Name = "btn7";
        btn7.Size = new Size(79, 25);
        btn7.TabIndex = 0;
        btn7.Text = "7";
        btn7.UseVisualStyleBackColor = true;
        btn7.Click += btnNumeroOperador_Click;
        btn8.Dock = DockStyle.Fill;
        btn8.Font = new Font("Segoe UI", 12F);
        btn8.Location = new Point(88, 3);
        btn8.Name = "btn8";
        btn8.Size = new Size(79, 25);
        btn8.TabIndex = 1;
        btn8.Text = "8";
        btn8.UseVisualStyleBackColor = true;
        btn8.Click += btnNumeroOperador_Click;
        btn9.Dock = DockStyle.Fill;
        btn9.Font = new Font("Segoe UI", 12F);
        btn9.Location = new Point(173, 3);
        btn9.Name = "btn9";
        btn9.Size = new Size(79, 25);
        btn9.TabIndex = 2;
        btn9.Text = "9";
        btn9.UseVisualStyleBackColor = true;
        btn9.Click += btnNumeroOperador_Click;
        btnDividir.Dock = DockStyle.Fill;
        btnDividir.Font = new Font("Segoe UI", 12F);
        btnDividir.Location = new Point(258, 3);
        btnDividir.Name = "btnDividir";
        btnDividir.Size = new Size(79, 25);
        btnDividir.TabIndex = 3;
        btnDividir.Text = "/";
        btnDividir.UseVisualStyleBackColor = true;
        btnDividir.Click += btnNumeroOperador_Click;
        btnAbrir.Dock = DockStyle.Fill;
        btnAbrir.Font = new Font("Segoe UI", 12F);
        btnAbrir.Location = new Point(343, 3);
        btnAbrir.Name = "btnAbrir";
        btnAbrir.Size = new Size(80, 25);
        btnAbrir.TabIndex = 4;
        btnAbrir.Text = "(";
        btnAbrir.UseVisualStyleBackColor = true;
        btnAbrir.Click += btnNumeroOperador_Click;
        btn4.Dock = DockStyle.Fill;
        btn4.Font = new Font("Segoe UI", 12F);
        btn4.Location = new Point(3, 34);
        btn4.Name = "btn4";
        btn4.Size = new Size(79, 25);
        btn4.TabIndex = 5;
        btn4.Text = "4";
        btn4.UseVisualStyleBackColor = true;
        btn4.Click += btnNumeroOperador_Click;
        btn5.Dock = DockStyle.Fill;
        btn5.Font = new Font("Segoe UI", 12F);
        btn5.Location = new Point(88, 34);
        btn5.Name = "btn5";
        btn5.Size = new Size(79, 25);
        btn5.TabIndex = 6;
        btn5.Text = "5";
        btn5.UseVisualStyleBackColor = true;
        btn5.Click += btnNumeroOperador_Click;
        btn6.Dock = DockStyle.Fill;
        btn6.Font = new Font("Segoe UI", 12F);
        btn6.Location = new Point(173, 34);
        btn6.Name = "btn6";
        btn6.Size = new Size(79, 25);
        btn6.TabIndex = 7;
        btn6.Text = "6";
        btn6.UseVisualStyleBackColor = true;
        btn6.Click += btnNumeroOperador_Click;
        btnMultiplicar.Dock = DockStyle.Fill;
        btnMultiplicar.Font = new Font("Segoe UI", 12F);
        btnMultiplicar.Location = new Point(258, 34);
        btnMultiplicar.Name = "btnMultiplicar";
        btnMultiplicar.Size = new Size(79, 25);
        btnMultiplicar.TabIndex = 8;
        btnMultiplicar.Text = "*";
        btnMultiplicar.UseVisualStyleBackColor = true;
        btnMultiplicar.Click += btnNumeroOperador_Click;
        btnFechar.Dock = DockStyle.Fill;
        btnFechar.Font = new Font("Segoe UI", 12F);
        btnFechar.Location = new Point(343, 34);
        btnFechar.Name = "btnFechar";
        btnFechar.Size = new Size(80, 25);
        btnFechar.TabIndex = 9;
        btnFechar.Text = ")";
        btnFechar.UseVisualStyleBackColor = true;
        btnFechar.Click += btnNumeroOperador_Click;
        btn1.Dock = DockStyle.Fill;
        btn1.Font = new Font("Segoe UI", 12F);
        btn1.Location = new Point(3, 65);
        btn1.Name = "btn1";
        btn1.Size = new Size(79, 25);
        btn1.TabIndex = 10;
        btn1.Text = "1";
        btn1.UseVisualStyleBackColor = true;
        btn1.Click += btnNumeroOperador_Click;
        btn2.Dock = DockStyle.Fill;
        btn2.Font = new Font("Segoe UI", 12F);
        btn2.Location = new Point(88, 65);
        btn2.Name = "btn2";
        btn2.Size = new Size(79, 25);
        btn2.TabIndex = 11;
        btn2.Text = "2";
        btn2.UseVisualStyleBackColor = true;
        btn2.Click += btnNumeroOperador_Click;
        btn3.Dock = DockStyle.Fill;
        btn3.Font = new Font("Segoe UI", 12F);
        btn3.Location = new Point(173, 65);
        btn3.Name = "btn3";
        btn3.Size = new Size(79, 25);
        btn3.TabIndex = 12;
        btn3.Text = "3";
        btn3.UseVisualStyleBackColor = true;
        btn3.Click += btnNumeroOperador_Click;
        btnSubtrair.Dock = DockStyle.Fill;
        btnSubtrair.Font = new Font("Segoe UI", 12F);
        btnSubtrair.Location = new Point(258, 65);
        btnSubtrair.Name = "btnSubtrair";
        btnSubtrair.Size = new Size(79, 25);
        btnSubtrair.TabIndex = 13;
        btnSubtrair.Text = "-";
        btnSubtrair.UseVisualStyleBackColor = true;
        btnSubtrair.Click += btnNumeroOperador_Click;
        btnPotencia.Dock = DockStyle.Fill;
        btnPotencia.Font = new Font("Segoe UI", 12F);
        btnPotencia.Location = new Point(343, 65);
        btnPotencia.Name = "btnPotencia";
        btnPotencia.Size = new Size(80, 25);
        btnPotencia.TabIndex = 14;
        btnPotencia.Text = "^";
        btnPotencia.UseVisualStyleBackColor = true;
        btnPotencia.Click += btnNumeroOperador_Click;
        btn0.Dock = DockStyle.Fill;
        btn0.Font = new Font("Segoe UI", 12F);
        btn0.Location = new Point(3, 96);
        btn0.Name = "btn0";
        btn0.Size = new Size(79, 25);
        btn0.TabIndex = 15;
        btn0.Text = "0";
        btn0.UseVisualStyleBackColor = true;
        btn0.Click += btnNumeroOperador_Click;
        btnVirgula.Dock = DockStyle.Fill;
        btnVirgula.Font = new Font("Segoe UI", 12F);
        btnVirgula.Location = new Point(88, 96);
        btnVirgula.Name = "btnVirgula";
        btnVirgula.Size = new Size(79, 25);
        btnVirgula.TabIndex = 16;
        btnVirgula.Text = ",";
        btnVirgula.UseVisualStyleBackColor = true;
        btnVirgula.Click += btnNumeroOperador_Click;
        btnSomar.Dock = DockStyle.Fill;
        btnSomar.Font = new Font("Segoe UI", 12F);
        btnSomar.Location = new Point(258, 96);
        btnSomar.Name = "btnSomar";
        btnSomar.Size = new Size(79, 25);
        btnSomar.TabIndex = 17;
        btnSomar.Text = "+";
        btnSomar.UseVisualStyleBackColor = true;
        btnSomar.Click += btnNumeroOperador_Click;
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(470, 550);
        Controls.Add(tableBotoes);
        Controls.Add(btnApagar);
        Controls.Add(btnLimpar);
        Controls.Add(btnIgual);
        Controls.Add(lbSequencias);
        Controls.Add(txtResultado);
        Controls.Add(txtVisor);
        FormBorderStyle = FormBorderStyle.FixedSingle;
        MaximizeBox = false;
        Name = "Form1";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "25736-24122-Calculadora";
        tableBotoes.ResumeLayout(false);
        ResumeLayout(false);
        PerformLayout();
    }


    private TextBox txtVisor;
    private TextBox txtResultado;
    private Label lbSequencias;
    private Button btnIgual;
    private Button btnLimpar;
    private Button btnApagar;
    private TableLayoutPanel tableBotoes;
    private Button btn7;
    private Button btn8;
    private Button btn9;
    private Button btnDividir;
    private Button btnAbrir;
    private Button btn4;
    private Button btn5;
    private Button btn6;
    private Button btnMultiplicar;
    private Button btnFechar;
    private Button btn1;
    private Button btn2;
    private Button btn3;
    private Button btnSubtrair;
    private Button btnPotencia;
    private Button btn0;
    private Button btnVirgula;
    private Button btnSomar;
}
